"""Switch to single day and add rotation_type

Revision ID: 8962020880de
Revises: f628f230e0c2
Create Date: 2025-04-21 22:30:18.641339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8962020880de'
down_revision = 'f628f230e0c2'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.String(length=100), nullable=False, server_default='Monday'))
        batch_op.add_column(sa.Column('rotation_type', sa.String(length=10), nullable=False, server_default='static'))



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.drop_column('rotation_type')
        batch_op.drop_column('day')

    # ### end Alembic commands ###
